host: 0.0.0.0
port: 8080
source:
  doc_id: s3_AecAfAazAEACND1DAzgQ1RzG1Np3v
  scode: ANoAZwcqAAw1tlXpxOAecAfAazAEA
  tab_id: tZdOxZ
  view_id: vtvpys
  name_field: 任务名称
  desc_field: 任务描述
  max_desc_len: 25
  start_field: 启动时间
  end_field: 预计完成时间
  person_field: 负责人
  status_field: 任务状态
  person_names:
  - 夏鑫
  status_values:
  - 进行中
  low_login_enable: '1'
  utype: ww
  TOK: dd22f988af820e2f
  traceid: dd22f988af
  hashkey: dd22f988
  tdoc_uid: '13102700534677199'
  wedoc_openid: wozbKqDgAACT29-f4esmoMcSuLRroAzw
  wedoc_sid: 1s9Kaoy_WnIu93Q4ADJ6dgAA
  wedoc_sids: 13102700534677199&1s9Kaoy_WnIu93Q4ADJ6dgAA
  wedoc_skey: 13102700534677199&91555cc70db899399c233d96387df129
  wedoc_ticket: 13102700534677199&CAESIHvXVZ-51PGcqqrPajTiWWLdUO0KZ8Cdvpgy_Q7geu6K
  language: zh-CN
  fingerprint: ''
target:
  url: https://oa.gbicc.cn
  login_path: login?redirect=%2Findex
  report_path: /project/prmProjectWorkLog
  username: xiaxin
  password: E7Rjmnp9BEFp
  default_project: 江苏信托开发技术服务项目2026
  page_timeout: 60000
  element_timeout: 15000
captcha:
  api_key: sk-cdccacaae68f4e5d977314a07496da12
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: qwen3-vl-flash
  prompt: '这是4位数字验证码，请仔细识别后只返回4位数字，不要其他内容。

    识别规则：

    - 长线先排除，字符分四区

    - 贯穿线条是干扰，成形才算数字

    - 闭圈辨0和8，带尾巴多是9

    - 右弧常为3，斜竖多1或7

    - 折角看作4，上弯下收是2

    '
wechat:
  corpid: wwf35acf2abf80360b
  corpsecret: dmiz23nCg6OtT56pnphVUk94LScSB_f3aV5r1uxhhzM
  agentid: 1000002
  token: rbjqr9999
  aes_key: L37GqJlVeGqqHPNb2E7b4aTIh4Z5avJAID2Bdhc2cLN
  to_user: XiaXin
scheduler:
  cookie_check_hour: 9
  cookie_check_minute: 45
  report_submit_hour: 17
  report_submit_minute: 56
  stats_push_hour: 18
  stats_push_minute: 10
  cache_cleanup_hour: 4
  cache_cleanup_minute: 0
nav_monitor:
  enabled: true
  push_hour: 8
  push_minute: 8
  evening_push_enabled: true
  evening_push_hour: 23
  evening_push_minute: 30
  estimate_enabled: true
  estimate_hour: 17
  estimate_minute: 30
  products:
  - provider: citic_wealth
    code: AF233276B
    name: 慧盈象固收增强一年持有期5号B
    shares: 478056.94
  - provider: nanyin_wealth
    code: A32069
    name: 南银理财悦稳最低持有91天3号-B份额
    shares: 100000.76
  - provider: citic_wealth
    code: AF252171L
    name: 安盈象固收稳利三个月持有期39号L
    shares: 88122.4
